#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

ConfigDir=$TEST_DIR/../../../../../../Examples/Text/PennTreebank/Config

# cntkrun <CNTK config file name> <additional CNTK args>
cntkrun rnn.cntk || exit $?

